/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

/**
 *
 * @author DAVID
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RESTAR = new javax.swing.JButton();
        C_CADENA = new javax.swing.JButton();
        COMPLEMENTO = new javax.swing.JButton();
        palindromo = new javax.swing.JButton();
        salir = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MAQUINA DE TURING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        RESTAR.setBackground(new java.awt.Color(255, 255, 255));
        RESTAR.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RESTAR.setText("Suma y Resta");
        RESTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTARActionPerformed(evt);
            }
        });
        getContentPane().add(RESTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 250, -1));

        C_CADENA.setBackground(new java.awt.Color(255, 255, 255));
        C_CADENA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        C_CADENA.setText("COPIAR");
        C_CADENA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_CADENAActionPerformed(evt);
            }
        });
        getContentPane().add(C_CADENA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 250, -1));

        COMPLEMENTO.setBackground(new java.awt.Color(255, 255, 255));
        COMPLEMENTO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        COMPLEMENTO.setText("COMPLEMENTO");
        COMPLEMENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMPLEMENTOActionPerformed(evt);
            }
        });
        getContentPane().add(COMPLEMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 250, 30));

        palindromo.setBackground(new java.awt.Color(255, 255, 255));
        palindromo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        palindromo.setText("Palindromo");
        palindromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palindromoActionPerformed(evt);
            }
        });
        getContentPane().add(palindromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 250, 40));

        salir.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("SALIR");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RESTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTARActionPerformed
        // TODO add your handling code here:
        RestaBinaria r = new RestaBinaria();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RESTARActionPerformed

    private void C_CADENAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_CADENAActionPerformed
        // TODO add your handling code here:
        CopiarCadena c = new CopiarCadena();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_C_CADENAActionPerformed

    private void COMPLEMENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMPLEMENTOActionPerformed
        // TODO add your handling code here:
        Complemento c = new Complemento();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_COMPLEMENTOActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void palindromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palindromoActionPerformed
        // TODO add your handling code here:
        palindromo p = new palindromo();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_palindromoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COMPLEMENTO;
    private javax.swing.JButton C_CADENA;
    private javax.swing.JButton RESTAR;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton palindromo;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
